server:
  port: 9001
spring:
  application:
    name: HRM-SYSMANAGE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_sysmanage?useSSL=false
    username: root
    password: 802134
mybatis-plus:
  mapper-locations: classpath:com/yogie/hrm/mapper/*Mapper.xml
  type-aliases-package: com.yogie.hrm.domain,com.yogie.hrm.query
